version: '3'
services:
  app:
    build: .
    volumes:
      - ./configs:/app/configs
      - ./credentials:/app/credentials
      - ./outputs:/app/outputs
    entrypoint: ["python3", "main.py", "--configs", "configs/main.yaml", "--mode", "all"]