name: Python App Workflow HeatGCalController

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run the script in dry-run mode (true/false)'
        required: true
        default: 'false'
      mode:
        description: 'Select mode to run the script'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - get_schedules
          - set_heaters
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  HEATZY_CREDENTIALS: ${{ secrets.HEATZY_CREDENTIALS }}
  STOVE_CREDENTIALS: ${{ secrets.STOVE_CREDENTIALS }}


jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Python script with or without --dry-run based on input
      - name: Run main.py with dry-run option
        run: |
          MODE="${{ github.event.inputs.mode }}"
          if [ "${{ github.event.inputs.dry-run }}" == "true" ]; then
            echo "Running in dry-run mode"
            python3 app/main.py --dry-run  --mode "$MODE"
          else
            echo "Running in normal mode"
            python3 app/main.py --mode "$MODE"
          fi
